In [11]:
#Matrices
import numpy as np;

arr1 = np.arange(0,20)
print("array")
print(arr1)

matrix1 = arr1.reshape(5,4)
print("\ndefault c like matrix")
print(matrix1)

# other way of calling reshape function
matrix2 = np.reshape(arr1, (5,4), 'F')
print("\nfortran like matrix")
print(matrix2)

array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

default c like matrix
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

fortran like matrix
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [14]:
r1=['I', 'am', 'inevitable']
r2=['I', 'am', 'iron man']
r3=[1,2,3]

#Note that all data types are now strings
matrix3 = np.array([r1,r2,r3])
print(matrix3)

[['I' 'am' 'inevitable']
 ['I' 'am' 'iron man']
 ['1' '2' '3']]


---

In [15]:
#Dictionaries
dict1 = {'key1':'val1','key2':'val2'}
print(dict1)

{'key1': 'val1', 'key2': 'val2'}


In [18]:
print(dict1['key1'])

val1
